### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by batden** [BodhiDev/bodhi_translations#6]
in landing.pot: "Bodhi uses _itables_..." -> iptables
in software.pot: "but this is beyond _is beyond_..." 
in index.pot: "...applications, and _file_ with the Quick Launcher!" -> files (?)

**Comment by josemanimala** [comment]
Will fix.

**Comment by hugok79** [comment]
also in software.pot: "Whichever method you choose to find your application, you will be presented with a link that leads to a page with a description of the _application_.." -> the are two dots in the end!

**Comment by josemanimala** [comment]
Fixed in #10
